java -jar agg.jar arrowleft_arm.gled arrowleft_arm.gif
java -jar agg.jar arrowleft_hat.gled arrowleft_hat.gif
java -jar agg.jar arrowleft_leg.gled arrowleft_leg.gif
java -jar agg.jar arrowleft_mtx.gled arrowleft_mtx.gif
java -jar agg.jar arrowright_arm.gled arrowright_arm.gif
java -jar agg.jar arrowright_hat.gled arrowright_hat.gif
java -jar agg.jar arrowright_leg.gled arrowright_leg.gif
java -jar agg.jar arrowright_mtx.gled arrowright_mtx.gif
java -jar agg.jar arrowup_arm.gled arrowup_arm.gif
java -jar agg.jar arrowup_hat.gled arrowup_hat.gif
java -jar agg.jar arrowup_leg.gled arrowup_leg.gif
java -jar agg.jar arrowup_mtx.gled arrowup_mtx.gif
java -jar agg.jar bell_arm.gled bell_arm.gif
java -jar agg.jar bell_hat.gled bell_hat.gif
java -jar agg.jar bell_leg.gled bell_leg.gif
java -jar agg.jar bell_mtx.gled bell_mtx.gif
java -jar agg.jar black_arm.gled black_arm.gif
java -jar agg.jar black_hat.gled black_hat.gif
java -jar agg.jar black_leg.gled black_leg.gif
java -jar agg.jar black_mtx.gled black_mtx.gif
java -jar agg.jar bulb_arm.gled bulb_arm.gif
java -jar agg.jar bulb_hat.gled bulb_hat.gif
java -jar agg.jar bulb_leg.gled bulb_leg.gif
java -jar agg.jar bulb_mtx.gled bulb_mtx.gif
java -jar agg.jar clocktree_arm.gled clocktree_arm.gif
java -jar agg.jar clocktree_hat.gled clocktree_hat.gif
java -jar agg.jar clocktree_leg.gled clocktree_leg.gif
java -jar agg.jar clocktree_mtx.gled clocktree_mtx.gif
java -jar agg.jar default_arm.gled default_arm.gif
java -jar agg.jar default_hat.gled default_hat.gif
java -jar agg.jar default_leg.gled default_leg.gif
java -jar agg.jar gift_mtx.gled gift_mtx.gif
java -jar agg.jar hahaha1_mtx.gled hahaha1_mtx.gif
java -jar agg.jar hahaha2_mtx.gled hahaha2_mtx.gif
java -jar agg.jar hahaha3_mtx.gled hahaha3_mtx.gif
java -jar agg.jar hahaha4_mtx.gled hahaha4_mtx.gif
java -jar agg.jar heart_arm.gled heart_arm.gif
java -jar agg.jar heart_hat.gled heart_hat.gif
java -jar agg.jar heart_leg.gled heart_leg.gif
java -jar agg.jar heart_mtx.gled heart_mtx.gif
java -jar agg.jar jesus1_mtx.gled jesus1_mtx.gif
java -jar agg.jar jesus2_mtx.gled jesus2_mtx.gif
java -jar agg.jar jesus3_mtx.gled jesus3_mtx.gif
java -jar agg.jar jesus4_mtx.gled jesus4_mtx.gif
java -jar agg.jar lightmeup_arm.gled lightmeup_arm.gif
java -jar agg.jar lightmeup_hat.gled lightmeup_hat.gif
java -jar agg.jar lightmeup_leg.gled lightmeup_leg.gif
java -jar agg.jar lightmeup_mtx.gled lightmeup_mtx.gif
java -jar agg.jar snowflakes_arm.gled snowflakes_arm.gif
java -jar agg.jar snowflakes_hat.gled snowflakes_hat.gif
java -jar agg.jar snowflakes_leg.gled snowflakes_leg.gif
java -jar agg.jar snowflakes_mtx.gled snowflakes_mtx.gif
java -jar agg.jar snowman_mtx.gled snowman_mtx.gif
java -jar agg.jar spiral_hat.gled spiral_hat.gif
java -jar agg.jar star_mtx.gled star_mtx.gif
java -jar agg.jar star_arm.gled years_arm.gif
java -jar agg.jar star_hat.gled years_hat.gif
java -jar agg.jar star_leg.gled years_leg.gif
java -jar agg.jar years1_mtx.gled years1_mtx.gif
java -jar agg.jar years2_mtx.gled years2_mtx.gif
java -jar agg.jar years3_mtx.gled years3_mtx.gif
java -jar agg.jar years4_mtx.gled years4_mtx.gif
java -jar agg.jar years1_arm.gled years_arm.gif
java -jar agg.jar years1_hat.gled years_hat.gif
java -jar agg.jar years1_leg.gled years_leg.gif
java -jar agg.jar years2_arm.gled years_arm.gif
java -jar agg.jar years2_hat.gled years_hat.gif
java -jar agg.jar years2_leg.gled years_leg.gif
java -jar agg.jar years3_arm.gled years_arm.gif
java -jar agg.jar years3_hat.gled years_hat.gif
java -jar agg.jar years3_leg.gled years_leg.gif
java -jar agg.jar years4_arm.gled years_arm.gif
java -jar agg.jar years4_hat.gled years_hat.gif
java -jar agg.jar years4_leg.gled years_leg.gif

copy /Y *.gled ..\light-node\data
